-- Dummy Developer
INSERT INTO DEVELOPER (NAME, ACTIVE) VALUES ('Deepkant', true);

-- Bug priorities
DELETE FROM BUG_PRIORITY;
INSERT INTO BUG_PRIORITY (DESCRIPTION) VALUES ('Critical');
INSERT INTO BUG_PRIORITY (DESCRIPTION) VALUES ('Major');
INSERT INTO BUG_PRIORITY (DESCRIPTION) VALUES ('Minor');

-- Bug statuses
DELETE FROM BUG_STATUS;
INSERT INTO BUG_STATUS (DESCRIPTION) VALUES ('New');
INSERT INTO BUG_STATUS (DESCRIPTION) VALUES ('Verified');
INSERT INTO BUG_STATUS (DESCRIPTION) VALUES ('Resolved');